### ISSUE TITLE
Add button for each experimentation.

### ISSUE THREAD

**Issue by Monal5031** [Monal5031/Js-css-Experimentations#4]
Each experimentation should have a button which will show/hide that experimentation.

**Comment by anshumanv** [comment]
One way could be to drag the entire experimentation off the screen using transform and on clicking the new made button we change the transform to drag it back to the screen, can we have an experiment with this work around ?

**Comment by Monal5031** [comment]
Well that is an experimentation in itself 😄 nice idea @Anshuman-Verma Will you work on it?

**Comment by anshumanv** [comment]
I'll give it a try, let's see if it works out.

**Comment by Monal5031** [comment]
@Anshuman-Verma Any ideas how it would look good?

**Comment by anshumanv** [comment]
Perhaps you have already done some implementation in this regard, the recent projects button that you have for various cards does onfold some data on clicking, maybe we can have a button that unfolds the card itself ?

**Comment by Monal5031** [comment]
Please send a PR @Anshuman-Verma

**Comment by anshumanv** [comment]
😕

**Comment by Monal5031** [comment]
Fixed in #8
