### ISSUE TITLE
Add a playlist experimentation

### ISSUE THREAD

**Issue by Monal5031** [Monal5031/Js-css-Experimentations#7]
Add a experimentation which will display the contents of a json into a playlist kind of way.

**Comment by akw105** [comment]
Hi, I'd like to have a go at this, what sort of contents will the json have? Are you after live data from an api or a custom json file that you can update?

**Comment by Monal5031** [comment]
Hello, thanks for showing interest in this project. There is no such data which I currently have, please go ahead by creating a custom json of yourself.
Edit: I'm unable to assign this issue maybe some bug of github, but go ahead send a PR 👍

**Comment by anshumanv** [comment]
@Amykw105 thanks for considering a contribution here, the exact problem is here https://github.com/anshumanv/ongaku we need to grab objects from data.json and display list of tracks in a div or sidenav also clicking on any link will play the corresponding track. 👍

**Comment by akw105** [comment]
Hey, no problem. Just so I'm clear, which repo am I sending a PR to? This one or Ongaku?

**Comment by anshumanv** [comment]
You can send PR in this repo and you can use https://github.com/anshumanv/ongaku/blob/master/js/data.json as a sample to implement this, once complete we'll incorporate it in ongaku, thanks 👍
